# Generated by Django 5.2.6 on 2025-09-25 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('upgrade_type', models.CharField(choices=[('health', 'Health'), ('speed', 'Speed'), ('damage', 'Damage')], max_length=20)),
                ('cost', models.IntegerField()),
                ('effect_value', models.IntegerField()),
                ('max_level', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('damage', models.IntegerField()),
                ('fire_rate', models.FloatField()),
                ('ammo_capacity', models.IntegerField()),
                ('unlock_wave', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_upgrades', models.IntegerField(default=0)),
                ('speed_upgrades', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='inventory.weapon')),
                ('unlocked_weapons', models.ManyToManyField(blank=True, to='inventory.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.upgrade')),
            ],
            options={
                'unique_together': {('player', 'upgrade')},
            },
        ),
    ]
